include:
  project: gardenlinux/gardenlinux-package-build
  file: pipeline/pipeline-git.yml

variables:
  SOURCE_NAME: 'metalbond'
  SOURCE_REPO: https://github.com/onmetal/metalbond
  BUILD_ARCH_ALL: ''
  BUILD_REQUIRES_GO: 'true'