variables:
  DEBFULLNAME: "Garden Linux builder"
  DEBEMAIL: "contact@gardenlinux.io"
  BUILD_ARCH_ALL: 'true'
  BUILD_ARCH_AMD64: 'true'
  BUILD_ARCH_ARM64: 'true'
  BUILD_SIGNED: ''
  ORIG_TAR: 'metalbond_0.2.0.orig.tar.gz'
  SOURCE_NAME: 'metalbond'

include:
- project: gardenlinux/gardenlinux-package-build
  ref: debug
  file:
  - pipeline/pipeline.yml      
