stages:
- download
- deploy


variables:
  DEBFULLNAME: "Garden Linux builder"
  DEBEMAIL: "contact@gardenlinux.io"
  BUILD_ARCH_ALL: 'true'
  BUILD_ARCH_AMD64: 'true'
  BUILD_ARCH_ARM64: ''
  BUILD_SIGNED: ''
  GITHUB_REPO: 'https://github.com/onmetal/metalbond'


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "lfs-storage"
      when: always
      

include:
- local: .gitlab/ci/download-release-artifacts.yml
#- project: gardenlinux/gardenlinux-package-build
#  file:
#  - pipeline/deploy.yml

